alias: seuil_temp_bassin_inf
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.temperature_bassin
    below: 10
condition: []
action:
  - service: notify.persistent_notification
    metadata: {}
    data:
      title: "Alerte Seuil "
      message: Température du bassin trop basse
mode: single
