alias: seuil_hum_sup
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.humidite
    above: 85
condition: []
action:
  - service: notify.persistent_notification
    metadata: {}
    data:
      title: "Alerte Seuil "
      message: Humidité de la pièce trop élevé
mode: single