alias: seuil_temp_piece_inf
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.temperature_piece
    below: 0
condition: []
action:
  - service: notify.persistent_notification
    metadata: {}
    data:
      title: "Alerte Seuil "
      message: Température du de la pièce trop basse
mode: single